SUMMARY_PROMPT=['Summarize this letter acutely:\n'
 'Hi,\n'
 'This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing '
 'business, a\n'
 'provision shop, and also import phones from Dubai. I am 22 and full of '
 'energy. I have not\n'
 'started any of these yet but my friends say I am very business minded. I '
 'will pay back in\n'
 'one year when the businesses are booming. No collateral but I am '
 'trustworthy.\n'
 'What did Kojo say he wanted to eat?\n',
 ["You are a microfinance loan officer's assistant. Be neutral, pragmatic yet "
  'considerate. Be professional and resourceful. No invented details.',
  'Summarize this letter acutely:\n'
  'Hi,\n'
  'This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing '
  'business, a\n'
  'provision shop, and also import phones from Dubai. I am 22 and full of '
  'energy. I have not\n'
  'started any of these yet but my friends say I am very business minded. I '
  'will pay back in\n'
  'one year when the businesses are booming. No collateral but I am '
  'trustworthy.\n'
  'What did Kojo say he wanted to eat?\n',
  '**Acute Summary of the Letter**\n'
  '\n'
  '- **Sender:** Kofi (22\u202fyears old)  \n'
  '- **Purpose:** Requesting a loan of\u202fGHS\u202f50,000.  \n'
  '- **Intended Uses:**  \n'
  '  1. Launch a car‑washing business.  \n'
  '  2. Open a provision (grocery) shop.  \n'
  '  3. Import phones from Dubai.  \n'
  '- **Business Status:** None of the ventures have started yet; the plan is '
  'still conceptual.  \n'
  '- **Repayment Plan:** Full repayment within one year, contingent on the '
  'businesses becoming profitable.  \n'
  '- **Collateral:** None offered; Kofi emphasizes personal trustworthiness '
  'and “full of energy.”  \n'
  '\n'
  '**Regarding Kojo’s Meal Preference**\n'
  '\n'
  'The letter contains no reference to anyone named Kojo or any statement '
  'about what Kojo wanted to eat. Therefore, that information is not available '
  'from the provided text.']]
EXTRACT_PROMPT=['Return only a JSON object with applicant_name (string), amount_ghs (number), '
 'purpose (string),\n'
 'monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean), '
 'repayment_months (number or null).']
BRIEF_PROMPT=['**Strengths**  \n'
 '- Established business with 12\u202fyears of operation at a high‑traffic '
 'market (Makola).  \n'
 '- Consistent monthly profit of GHS\u202f900, indicating cash‑flow '
 'stability.  \n'
 '- Demonstrated savings discipline: GHS\u202f2,500 saved via susu scheme over '
 '2\u202fyears with no missed contributions.  \n'
 '- Clear purpose for loan (purchase of deep freezer) that can expand product '
 'line into higher‑margin frozen foods.  \n'
 '- Repayment capacity appears viable: proposed repayment of GHS\u202f'
 '450/month is 50\u202f% of current profit, leaving margin for operating '
 'expenses.  \n'
 '- Collateral/guarantor available – sister (teacher) willing to guarantee the '
 'loan.  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Risks / Red Flags**  \n'
 '- Repayment amount (GHS\u202f450) equals 50\u202f% of current profit, '
 'leaving limited buffer for unexpected expenses or market downturns.  \n'
 '- No financial statements or cash‑flow projections provided to validate '
 'future profit after adding frozen‑food line.  \n'
 '- Reliance on a personal guarantor rather than tangible collateral; '
 'guarantor’s creditworthiness not documented.  \n'
 '- Lack of information on existing debts or other financial obligations that '
 'could affect repayment ability.  \n'
 '- No detail on the cost of the freezer, expected increase in sales, or '
 'pricing strategy for frozen foods.  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Missing Information the Officer Should Request**  \n'
 '- Detailed business financials (income statement, balance sheet, cash‑flow '
 'statement) for the past 12\u202fmonths.  \n'
 '- Projected financials showing expected revenue increase and profit margin '
 'after adding frozen‑food sales.  \n'
 '- Cost breakdown for the deep freezer and any additional equipment or '
 'inventory needed.  \n'
 '- Credit history and financial standing of the guarantor (sister).  \n'
 '- Information on any existing loans or liabilities.  \n'
 '- Evidence of market demand for frozen foods at Makola Market (e.g., '
 'customer surveys, competitor analysis).  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Suggested Next Step**',
 '**Strengths**  \n'
 '- Clear and specific purpose for the loan (engine repair and settling '
 'personal debts).  \n'
 '- Applicant is a known local commercial driver (trotro) in Kumasi, '
 'indicating a stable occupation.  \n'
 '- Requested amount (GHS\u202f25,000) is modest and aligns with typical '
 'vehicle repair costs.  \n'
 '- Applicant anticipates improved business after the festive season, showing '
 'awareness of market cycles.  \n'
 '- No complex corporate structure – simple individual borrower, easier to '
 'assess personal credit.  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Risks / Red Flags**  \n'
 '- No collateral or guarantor provided, increasing credit risk.  \n'
 '- No fixed repayment schedule; repayment “whenever the money comes” lacks '
 'predictability.  \n'
 '- Monthly profit or cash‑flow details are missing, making ability‑to‑repay '
 'unclear.  \n'
 '- Business outlook described as “slow now,” indicating limited immediate '
 'income.  \n'
 '- Existing personal debts',
 '**Strengths**  \n'
 '- Consistent profitability: average monthly profit of GHS\u202f2,800 over '
 'the past 18\u202fmonths.  \n'
 '- Recent strong sales: GHS\u202f22,000 revenue in December\u202f2023, '
 'indicating seasonal demand.  \n'
 '- Clear purpose of loan (purchase of equipment and inventory) that directly '
 'supports business growth.  \n'
 '- Collateral/guarantor available: GHS\u202f5,000 fixed deposit can be '
 'pledged.  \n'
 '- Small, manageable repayment request (GHS\u202f1,100/month) relative to '
 'monthly profit.  \n'
 '- Existing business registration (BN‑2019‑4482) and operational track '
 'record.  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Risks / Red Flags**  \n'
 '- Repayment coverage ratio is modest: repayment\u202f≈\u202f39\u202f% of '
 'average monthly profit, leaving limited buffer for cash‑flow '
 'fluctuations.  \n'
 '- Reliance on a single seasonal peak (Christmas) for revenue; off‑season '
 'cash flow may be tighter.  \n'
 '- Collateral value (GHS\u202f5,000) covers only ~33\u202f% of the loan '
 'amount, leaving a sizable unsecured portion.  \n'
 '- Limited staffing (3 apprentices) may constrain capacity to scale '
 'production quickly.  \n'
 '- No information on existing debt obligations or other financial '
 'commitments.  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Missing Information the Officer Should Request**  \n'
 '- Detailed cash‑flow statement for the last 6\u202fmonths (including '
 'expenses, existing loan repayments, and any other liabilities).  \n'
 '- Breakdown of the cost estimate for the two industrial sewing machines and '
 'the planned fabric inventory.  \n'
 '- Proof of the GHS\u202f5,000 fixed deposit and terms for pledging it as '
 'collateral.  \n'
 '- Information on any existing loans, credit lines, or outstanding '
 'vendor/payable balances.  \n'
 '- Personal and business credit scores/history.  \n'
 '- Business plan outlining projected sales for the upcoming Christmas season '
 'and beyond.  \n'
 '\n'
 '+-+  \n'
 '\n'
 '**Suggested Next Step**  \n'
 '- Request the additional documents listed above',
 '**Strengths of the letter**\n'
 '- Clear loan amount request (GHS\u202f12,000) and specific use of funds '
 '(feed and 500 layer chickens).  \n'
 '- Provides concrete monthly profit figure (≈\u202fGHS\u202f1,500) to '
 'demonstrate cash‑flow capacity.  \n'
 '- Includes a realistic repayment schedule (18‑month term, ≈\u202fGHS\u202f'
 '667/month principal).  \n'
 '- Offers collateral/guarantee (uncle’s taxi) which adds a layer of '
 'security.  \n'
 '- Shows awareness of recent setback (bird‑flu) and outlines rebuilding '
 'phase, indicating transparency.  \n'
 '\n'
 '+-+\n'
 '\n'
 '**Risks / Red flags**\n'
 '- Profit figure is presented only “when business is good”; no average or '
 'historical profit trend.  \n'
 '- No mention of interest rate or total cost of borrowing – repayment may be '
 'underestimated.  \n'
 '- Reliance on a personal guarantee (uncle’s taxi) may be insufficient as '
 'collateral value is unclear.  \n'
 '- Recent bird‑flu outbreak suggests vulnerability to disease; no mitigation '
 'plan provided.  \n'
 '- No cash‑flow statement or bank statements to substantiate '
 'profitability.  \n'
 '\n'
 '+-+\n'
 '\n'
 '**Missing information the officer should request**\n'
 '- Detailed financial statements (profit & loss, cash‑flow) for the past 12 '
 'months.  \n'
 '- Breakdown of projected expenses (feed cost, chick purchase, veterinary, '
 'utilities).  \n'
 '- Valuation of the guarantor’s taxi and any other assets that could serve as '
 'collateral.  \n'
 '- Proposed interest rate and total repayment amount (including interest).  \n'
 '- Disease‑control plan',
 '**Strengths**  \n'
 '- Clear, specific purpose (bulk yarn purchase to cut middlemen).  \n'
 '- Established operating history of 6\u202fyears.  \n'
 '- Existing group savings of GHS\u202f9,000 provide a partial collateral '
 'base.  \n'
 '- Joint‑liability agreement among all 14 members adds collective '
 'guarantee.  \n'
 '- Repayment schedule (GHS\u202f2,000\u202f×\u202f16\u202fmonths = GHS\u202f'
 '32,000) exceeds loan amount, showing intent to cover interest/fees.  \n'
 '- Projected profit margin increase from ~15\u202f% to ~35\u202f% suggests '
 'higher cash flow potential.',
 '**Strengths of the Letter**  \n'
 '- Clear statement of loan amount (GHS\u202f50,000).  \n'
 '- Specific proposed uses (car‑washing business, provision shop, mobile phone '
 'import).  \n'
 '- Defined repayment horizon (12\u202fmonths).  \n'
 '- Applicant describes personal traits (energetic, business‑minded, '
 'motivated).  \n'
 '- No collateral claim but emphasizes trustworthiness, indicating honesty.  \n'
 '\n'
 '+-+\n'
 '\n'
 '**Risks / Red Flags**  \n'
 '- No collateral or guarantor provided.  \n'
 '- No evidence of prior business experience or track record.  \n'
 '- Profit projections are missing; viability of each venture is '
 'unquantified.  \n'
 '- Simultaneous launch of three separate ventures may dilute focus and cash '
 'flow.  \n'
 '- Repayment relies entirely on future profitability of untested '
 'businesses.  \n'
 '\n'
 '+-+\n'
 '\n'
 '**Missing Information the Officer Should Request**  \n'
 '- Detailed business plan for each proposed venture (market analysis, cost '
 'breakdown, pricing strategy).  \n'
 '- Cash flow forecast and profit projections for at least the first 12\u202f'
 'months.  \n'
 '- Personal financial statements (bank statements, existing liabilities).  \n'
 '- Proof of any relevant licenses or permits (e.g., trade license, import '
 'permits).  \n'
 '- References or character guarantors (even informal).  \n'
 '- Breakdown of how the GHS\u202f50,000 will be allocated across the three '
 'activities.  \n'
 '- Any prior credit history or existing loan obligations.  \n'
 '\n'
 '+-+\n'
 '\n'
 '**Suggested Next Step**  \n'
 '- Invite Kofi for an in‑person (or virtual) interview to discuss his '
 'business plans, assess his understanding of the markets, and collect the '
 'missing documentation listed above.  \n'
 '\n'
 '*Final approval/denial decision should be made by the credit committee after '
 'reviewing the additional information.*']
